namespace: community
name: azure
version: 0.1.0
readme: README.md
authors:
  - Ansible (github.com/ansible)
description: null
license_file: COPYING
tags: null
#dependencies:
#  azure.azcollection: '>=0.1.0'
repository: https://github.com:ansible-collections/community.azure
documentation: https://github.com/ansible-collection-migration/community.azure/tree/master/docs
homepage: https://github.com/ansible-collections/community.azure
issues: https://github.com/ansible-collections/community.azure/issues
